import React, { useState, Component } from 'react';
import PropTypes from 'prop-types';
import emoji from 'emoji-dictionary';
import './NewCardForm.css';

const EMOJI_LIST = ["", "heart_eyes", "beer", "clap", "sparkling_heart", "heart_eyes_cat", "dog"]


const NewCardForm = (props) => {

  const [newCard, setNewCard] = useState({
    //id generated by API
    text: '',
    emoji: '',
  })

  const onInputChange = (event) => {
    const newCardFields = {
      ...newCard,
    }
    newCardFields[event.target.name] = event.target.value;
    setNewCard(newCardFields);
  }

  const onFormSubmit = (event) => {
    event.preventDefault();

    props.addCardCallback(newCard);

    setNewCard({
      text: '',
      emoji: '',
    });

  }

  return(
    <div className="new-card-form">
      <header className="new-card-form__header">
        <h1>Submit a Card!</h1>
      </header>
      <form className="new-card-form__form" onSubmit={onFormSubmit}>
        
        <label className="new-card-form__form-label">Enter Text : </label>
        <input className="new-card-form__form-textarea"
               id="text"
               name="text"
               onChange={onInputChange}
               value={newCard.text}
        />

        <label className="new-card-form__form-label">Pick Emoji : </label>
        <select className="new-card-form__form-select"
                id="emoji"
                name="emoji"
                onChange={onInputChange}
                value={newCard.emoji}
        >
          {EMOJI_LIST.map(emojiText => <option value={emojiText} key={emojiText}> {emoji.getUnicode(emojiText)} </option>)}
        </select>

        <input className="new-card-form__form-button"
        type="submit"
        value="Submit"
      />
      </form>
    </div>

  )
}

export default NewCardForm;

NewCardForm.propTypes = {
  addCardCallback: PropTypes.func.isRequired,
}